// Metadata is generated by the Next.js route layer. This compatibility helper
// keeps the existing page components unchanged while avoiding client-side head mutations.
export function setPageMeta(title: string, description: string) {
  void title;
  void description;
}
